### ISSUE TITLE
led.system producer.cpp unregproduce 내부 로직 검토 요청

### ISSUE THREAD

**Issue by timedaimon** [ibct-dev/led.public.contracts#15]
auto itr = _producers.find( producer.value );
...
 _producers.erase( itr );
... 
 const auto& prod = _producers.get( producer.value, "producer not found" );
 
 producer.value로 이미 erase를 진행한 후 다시 producer.value로 검색을 진행하고 있어 
 "producer not found" 발생

이후 frontier, interior 테이블 업데이트 진행 불가능

**Comment by chonbyungkwon** [comment]
_producers.erase( itr );  이 로직을 
_frontiers, _interior 삭제 이후로 변경 함

**Comment by chobyungkwon** [comment]
_producers.erase( itr ); 이 로직을
_frontiers, _interior 삭제 이후로 변경 함
